### ISSUE TITLE
What's build

### ISSUE THREAD

**Issue by yuzhichang** [haproxytech/dataplaneapi-specification#1]
Where does the binary file `build` come from? Can it be replaced with some open-source tool such as go-swagger?

**Comment by mjuraga** [comment]
It is a small binary I wrote myself in go, cause the go-swagger didn't work with $refs that point to external files. This just builds the yaml in /build dir and then this yaml can be used with go-swagger.

**Comment by yuzhichang** [comment]
Can you open-source `build`?

**Comment by mjuraga** [comment]
I added build source with https://github.com/haproxytech/dataplaneapi-specification/commit/b650a9b39898e1c43b85ef4f8e5650542428c280
